COPS-IITBHU/csoc-2021-task-1

- Android.md
[Repo](https://github.com/RainaJain5/TicTacToe)
[APK|Web Site](https://github.com/RainaJain5/TicTacToe/blob/master/TicTacToe.apk)
> TicTacToe Android

- Android.md
[Repo](https://github.com/mihir02badkur/Tic-Tac-Toe)
[APK|Web Site](https://github.com/mihir02badkur/Tic-Tac-Toe/blob/master/TIC-TAC-TOE.apk)
> tictactoeByMihir

- Android.md
> Ayushigupta931 tic tac toe

- Android.md
[Repo](https://github.com/ayushigupta931/Tic_-.Tac_-.Toe04)
[APK|Web Site](https://github.com/ayushigupta931/Tic_-.Tac_-.Toe04/blob/master/app-debug.apk)
> TIc Tac Toe Android

- Android.md
[Repo](https://github.com/puranjayK/TicTacToe)
[APK|Web Site](https://github.com/puranjayK/TicTacToe/blob/main/APK/TicTacToe.apk)
> Added Repo and APK link

- WebDev.md
> added repo and site link

- WebDev.md
[Repo](https://github.com/Divyansh013/Tic-Tac-Toe)
[APK|Web Site](https://divyansh013.github.io/Tic-Tac-Toe/)
> Added repo name,link and site link

- WebDev.md
[Repo](https://github.com/manu-shukla/Tic-Tac-Toe)
[APK|Web Site](https://manu-shukla.github.io/Tic-Tac-Toe/)
> Added Tic Tac Toe

- Flutter.md
[tic-tac-toe_Chirayu](https://github.com/chirayumit001/csoc-2021-task-1.git)
[APK|Web Site](https://mine-tic-tac-toe-game.netlify.app/#/)
> Chirayu_Mittal_Tic_Tac_Toe

- Flutter.md
[Repo](https://github.com/parthb83/tic_tac_toe)
[APK|Web Site](https://github.com/parthb83/tic_tac_toe/blob/master/app-release.apk)
> Added repository name and link and apk link.

- WebDev.md
[Repo](https://github.com/somesh202/Tic-Tac-Toe)
[APK|Web Site](https://somesh202.github.io/Tic-Tac-Toe/)
> Added repo and website link

- WebDev.md
[Repo](https://github.com/debarati-06/tic-tac-toe)
[APK|Web Site](https://debarati-06.github.io/tic-tac-toe/)
> Tic-Tac-Toe_Debarati

- WebDev.md
Added few Changes
Deepak Verma - [github Repo](https://github.com/Deepakv14/TicTacToeFinal.github.io) [Web Site](https://deepakv14.github.io/TicTacToeFinal.github.io/)
> Deepak | Tic Tac Toe

- WebDev.md
[Repo](https://github.com/shukapurv/Tic-Tac-Toe_game)
[APK|Web Site](https://shukapurv.github.io/Tic-Tac-Toe_game/)
> Added link of repo and site in WebDev.md

- Flutter.md
[Repo](https://github.com/dev-raj-1729/flutter-tic-tac-toe)
[APK|Web Site](https://github.com/dev-raj-1729/hello-world/blob/4fcb8a45ae3215ba385a6799e874d812ead23b53/app-release.apk)
> Added my Flutter Tic Tac Toe Submission

- Flutter.md
[CSOC-Week1-Tic-Tac-Toe-Flutter](https://github.com/dhruxy/CSOC-Week1-Tic-Tac-Toe-Flutter)
[APK|Web Site](https://github.com/dhruxy/CSOC-Week1-Tic-Tac-Toe-Flutter/blob/main/app-release.apk)
> Added entry in flutter.md

- Flutter.md
[Repo](https://github.com/parthg48/tictactoe_flutter)
> Parth Gupta Tic Tac Toe

- Flutter.md
[Repo]https://github.com/singhdhroov/Tictactoe.git
[APK|Web Site]https://github.com/singhdhroov/Tictactoe/blob/master/app-release.apk
> added submission detail

- Flutter.md
> Pawan Kumar

- WebDev.md
[Repo](https://github.com/shubhangi013/TicTacToe)
[APK|Web Site](https://shubhangi013.github.io/TicTacToe/)
> added repo and site link for task1

- .github/PULL_REQUEST_TEMPLATE.md
- WebDev.md
[Repo](https://github.com/aditya-chhaparia/csoc-2021-task-1)
[Web Site](https://aditya-chhaparia.github.io/sudoku-game/)
> Added name, repo name and site-link

- WebDev.md
> Added Name,Repo Name & Link, and Page link

- WebDev.md
[Repo](https://github.com/try-catch-stack/Tic-Tac-Toe)
[APK|Web Site](https://try-catch-stack.github.io/Tic-Tac-Toe/)
> Add my site and repo link

- WebDev.md
> Tic-Tac-Toe Game (WebDev)

- WebDev.md
> 1st commit

- WebDev.md
I found it difficult to use objects in Javascript to implement the random board generator. Since time was short, I commented out the random generator code and used a static board instead.
> Added the Sudoku Website for Pratik Mishra.

- WebDev.md
> Manali's Sudoku Game

- WebDev.md
[Repo](https://github.com/it-is-skywalkerl/Sudoku-Game)
[APK|Web Site](https://it-is-skywalkerl.github.io/Sudoku-Game/)
> Sudoku Web Dev

- .github/PULL_REQUEST_TEMPLATE.md
- WebDev.md
[Repo](https://github.com/Majesty-12/Tic-Tac-Toe)
[APK|Web Site](https://naveen-tic-tac-toe.netlify.app)
> Tic-Tac-Toe by Majesty-12

- WebDev.md
may use backtracking or naive approaches to generate the board.
[Repo](https://github.com/lelouch-of-the-code/csoc-week1-wd)
[APK|Web Site](https://anii-sudoku.netlify.app/)
> (web) added repo, live site for sudoku
